version: '3'

services:
  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    container_name: langfuse
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
    networks:
      - llm-net
    depends_on:
      - postgres
    

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=langfuse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - llm-net

networks:
  llm-net:
    external: true

volumes:
  postgres_data: