version: "3.4"

services:
  otel-collector:
    container_name: otel-collector
    cpus: 0.1
    mem_limit: 100m
    build:
      context: .
    ports:
      - 8888:8888   # Prometheus metrics exposed by the Collector
      - 8889:8889   # Prometheus exporter metrics
      - 13133:13133 # health_check extension (/health/status)
    restart: always
    networks:
      - llm-net
  
networks:
  llm-net:
    external: true