# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:

  # Configuration Prometheus
  - uid: prometheus
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID
      httpMethod: POST
    readOnly: false
    editable: true

  # Configuration Grafana Tempo
  - uid: tempo
    name: Tempo
    type: tempo
    typeName: Tempo
    url: http://tempo:3200
    jsonData:
      tracesToLogs:
          datasourceUid: 'loki'
          mappedTags: [{ key: 'service.name', value: 'job' }]
          mapTagNamesEnabled: true
          filterByTraceID: true
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'
    readOnly: false
    editable: true

  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"traceid\":\"([^\"]+)\""
          #(?:trace_id)=(\w+)
          name: TraceID
          url: $${__value.raw}
    readOnly: false
    editable: true