apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: cpfl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: cpfl
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      imagePullSecrets:
        - name: secret-dockerhub
      containers:
        - name: loki
          image: loki:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3100   # otlp grpc 
          - containerPort: 9095   # otlp http
          resources:
            limits:
              cpu: "2"
              memory:  1024Mi
            requests:
              cpu: "0.1"
              memory:  100Mi
          volumeMounts:
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: cpfl
spec:
  selector:
    app: loki
  ports:
    - name: prometheus-metrics-collector
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: prometheus-metrics-exporter
      protocol: TCP
      port: 9095
      targetPort: 9095
